export default {
  ic_full_logo: require('./../assets/images/full-logo.png'),
  ic_logo: require('./../assets/images/logo.png'),

  ic_chat: require('./../assets/images/Chat.png'),
  ic_chat_inactive: require('./../assets/images/Chat-inactive.png'),
  ic_mail_inactive: require('./../assets/images/Mail-inactive.png'),
  ic_user: require('./../assets/images/User.png'),
  ic_email: require('./../assets/images/Email.png'),
  ic_password: require('./../assets/images/Password.png'),

  ic_user_simple: require('./../assets/images/User-simple.png'),
  ic_edit: require('./../assets/images/edit.png'),
  ic_info: require('./../assets/images/info.png'),
  ic_search: require('./../assets/images/search.png'),
  ic_options_vertical: require('./../assets/images/options-vertical.png'),
  ic_options_vertical_inactive: require('./../assets/images/options-vertical-inactive.png'),
  ic_seen: require('./../assets/images/Seen.png'),
  ic_camera: require('./../assets/images/Camera.png'),
  ic_gallery: require('./../assets/images/gallery.png'),
  ic_recording: require('./../assets/images/recording.png'),
  ic_calendar: require('./../assets/images/calendar.png'),

  ic_gender: require('./../assets/images/gender.png'),
  ic_race: require('./../assets/images/race.png'),
  ic_education: require('./../assets/images/education.png'),
  ic_married: require('./../assets/images/married.png'),
  ic_height: require('./../assets/images/height.png'),
  ic_weight: require('./../assets/images/weight.png'),
  ic_exercise: require('./../assets/images/exercise.png'),
  ic_health: require('./../assets/images/health.png'),
  ic_alcohol: require('./../assets/images/alcohol.png'),
  ic_smoke: require('./../assets/images/smoke.png'),
  ic_no_smoke: require('./../assets/images/no_smoke.png'),
  
  ic_underweight: require('./../assets/images/underweight.png'),
  ic_normal: require('./../assets/images/normal.png'),
  ic_overweight: require('./../assets/images/overweight.png'),
  ic_obese: require('./../assets/images/obese.png'),
  ic_extremely_obese: require('./../assets/images/extremely_obese.png'),


  ic_running: require('./../assets/images/running.png'),
  ic_alarm: require('./../assets/images/alarm.png'),
  ic_alarm_disable: require('./../assets/images/alarm_disable.png'),
  ic_clock: require('./../assets/images/clock.png'),
  ic_clock_disable: require('./../assets/images/clock_disable.png'),
  ic_back: require('./../assets/images/back.png'),
  ic_next: require('./../assets/images/next.png'),
  ic_home: require('./../assets/images/home.png'),
  ic_share: require('./../assets/images/share.png'),
  ic_youtube: require('./../assets/images/youtube.png'),
  ic_remove: require('./../assets/images/remove.png'),
  ic_add: require('./../assets/images/add.png'),
  ic_check: require('./../assets/images/check.png'),
  ic_music_symbol: require('./../assets/images/ic_music_symbol.png'),
  ic_skip_previous: require('./../assets/images/ic_previous.png'),
  ic_skip_next: require('./../assets/images/ic_next.png'),
  ic_pause: require('./../assets/images/ic_pause.png'),
  ic_play: require('./../assets/images/ic_play.png'),
  ic_music: require('./../assets/images/ic_music_symbol.png'),
  ic_video: require('./../assets/images/videoplay.png'),
  ic_local_import: require('./../assets/images/local_import.png'),
  ic_file_open: require('./../assets/images/file_open.png'),
  ic_chevron_left: require('./../assets/images/chevron_left.png'),
  ic_search_disable: require('./../assets/images/search_disable.png'),
  ic_search_enable: require('./../assets/images/search_enable.png'),
  default_avatar: require('./../assets/images/default_avatar.png'),
  ic_lifespan_active: require('./../assets/images/lifespan_active.png'),
  ic_lifespan_disable: require('./../assets/images/lifespan_disable.png'),
  ic_funeral_active: require('./../assets/images/funeral_active.png'),
  ic_funeral_disable: require('./../assets/images/funeral_disable.png'),
  ic_share_active: require('./../assets/images/share_active.png'),
  ic_share_disable: require('./../assets/images/share_disable.png'),
  ic_account_active: require('./../assets/images/account_active.png'),
  ic_account_disable: require('./../assets/images/account_disable.png'),
  ic_eye_active: require('./../assets/images/eye_active.png'),
  ic_top_wish: require('./../assets/images/topwish.png'),
  ic_funeral_song: require('./../assets/images/song.png'),
  ic_speaker: require('./../assets/images/speaker.png'),
  ic_pallbearer: require('./../assets/images/pallbearer.png'),
  ic_lifevideo: require('./../assets/images/lifevideo.png'),
  ic_logout: require('./../assets/images/logout.png')
};
