export default {
  ic_full_logo: require('./../assets/images/full-logo.png'),
  ic_logo: require('./../assets/images/logo.png'),
  ic_logo_dark: require('./../assets/images/logo-dark.png'),

  ic_chat: require('./../assets/images/Chat.png'),
  ic_chat_inactive: require('./../assets/images/Chat-inactive.png'),
  ic_mail: require('./../assets/images/Mail.png'),
  ic_mail_inactive: require('./../assets/images/Mail-inactive.png'),
  ic_user: require('./../assets/images/User.png'),
  ic_user_inactive: require('./../assets/images/User-inactive.png'),
  ic_email: require('./../assets/images/Email.png'),
  ic_password: require('./../assets/images/Password.png'),
  ic_watch: require('./../assets/images/Watch.png'),
  ic_watch_inactive: require('./../assets/images/Watch-inactive.png'),
  ic_phone: require('./../assets/images/Phone.png'),
  ic_phone_inactive: require('./../assets/images/Phone-inactive.png'),

  ic_user_simple: require('./../assets/images/User-simple.png'),
  ic_edit: require('./../assets/images/edit.png'),
  ic_info: require('./../assets/images/info.png'),
  ic_chevron_right: require('./../assets/images/chevron-right.png'),
  ic_chevron_right_grey: require('./../assets/images/chevron-right-grey.png'),
  ic_chevron_left: require('./../assets/images/chevron-left.png'),
  ic_search: require('./../assets/images/search.png'),
  ic_webcam: require('./../assets/images/webcam.png'),
  ic_export: require('./../assets/images/export.png'),
  ic_options_vertical: require('./../assets/images/options-vertical.png'),
  ic_options_vertical_inactive: require('./../assets/images/options-vertical-inactive.png'),
  ic_seen: require('./../assets/images/Seen.png'),
  ic_camera: require('./../assets/images/Camera.png'),
  ic_voice: require('./../assets/images/voice.png'),
  ic_recording: require('./../assets/images/recording.png'),
  ic_calendar: require('./../assets/images/calendar.png'),
  ic_running: require('./../assets/images/running.png'),
  ic_alarm: require('./../assets/images/alarm.png'),
  ic_back: require('./../assets/images/back.png'),
  ic_next: require('./../assets/images/next.png'),
  ic_home: require('./../assets/images/home.png'),
  ic_share: require('./../assets/images/share.png'),
  ic_youtube: require('./../assets/images/youtube.png'),
  ic_remove: require('./../assets/images/remove.png'),
  default_thumbnail: require('./../assets/images/default_thumbnail.png'),
  ic_react_smile: require('./../assets/images/react-smile.png'),

  template_user: require('./../assets/images/template-user.png'),
  template_graph: require('./../assets/images/template-graph.png'),
};
